#!/bin/env python3
import paho.mqtt.client as mqtt
import re, datetime, http.server

unlocks = [""] *10

def on_message(client, obj, msg):
    if "opt-" not in msg.topic:
        unlocks.pop(0)
        name = re.search(r"/.+/(.+)/", msg.topic).group(1)
        text = f"<{datetime.datetime.now():%Y-%m-%d %H:%M:%S}> {name} unlocked by {msg.payload.decode()}"
        unlocks.append(text)
        print(text)

class RequestHandler(http.server.BaseHTTPRequestHandler):
        def do_GET(self):
            self.send_response(200)
            self.send_header("Content-type", "text/html; charset=utf-8")
            self.end_headers()
            self.wfile.write("<br />".join(unlocks+[""]).encode())

httpd = http.server.HTTPServer(('0.0.0.0', 8000), RequestHandler)
httpd.timeout = 0.05

mqttc = mqtt.Client()
mqttc.message_callback_add("revspace-local/doorduino/+/unlocked", on_message)
mqttc.connect("mosquitto.space.revspace.nl")
mqttc.subscribe("revspace-local/doorduino/+/unlocked")

while True:
    httpd.handle_request()
    mqttc.loop(timeout=0.05)
