#!/usr/bin/env python3
import paho.mqtt.client, http.server, datetime, sys, html

print("[{:%Y-%m-%d %H:%M:%S.%f}] Starting...".format(datetime.datetime.now()))

unlocks = [""] *20

def on_message(client, obj, msg):
    if "opt-" not in msg.topic:
        unlocks.pop(0)
        text = "<{:%Y-%m-%d %H:%M:%S}> {} unlocked by {}".format(datetime.datetime.now(), msg.topic.split('/')[2], msg.payload.decode())
        unlocks.append(html.escape(text))
        print(text)

class RequestHandler(http.server.BaseHTTPRequestHandler):
        def do_GET(self):
            try:
                self.send_response(200)
                self.send_header("Content-type", "text/html; charset=utf-8")
                self.send_header("Access-Control-Allow-Origin", "*")
                self.end_headers()
                self.wfile.write("<br />".join(unlocks+[""]).encode())
            except BrokenPipeError:
                print("B0rken pipe. Client disconnected during request processing?")

httpd = http.server.HTTPServer(('0.0.0.0', 42042), RequestHandler)
httpd.timeout = 0.05

sub_topic = "revspace-local/doorduino/+/unlocked"

mqttc = paho.mqtt.client.Client()
mqttc.message_callback_add(sub_topic, on_message)
try:
    mqttc.connect("mosquitto.space.revspace.nl")
except ConnectionRefusedError:
    print("MQTT connection refused. Are you inside the RevSpace network?")
    sys.exit(42)
mqttc.subscribe(sub_topic)

print("[{:%Y-%m-%d %H:%M:%S.%f}] Started".format(datetime.datetime.now()))

try:
    while True:
        httpd.handle_request()
        mqttc.loop(timeout=0.05)
except KeyboardInterrupt:
    print("Bye!")
